import { createFileRoute, Navigate } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { collection, getDocs, query, orderBy, setDoc, doc, serverTimestamp, where } from "firebase/firestore";
import { db } from "@/services/firestore/client";
import { useAuth } from "@/lib/auth";
import { initializeApp } from "firebase/app";
import { getAuth, createUserWithEmailAndPassword } from "firebase/auth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useState } from "react";
import { toast } from "sonner";
import { Loader2, Plus, X } from "lucide-react";

export const Route = createFileRoute("/_app/users")({
  component: UsersPage,
});

function UsersPage() {
  const { role, loading } = useAuth();
  const queryClient = useQueryClient();
  const [isAdding, setIsAdding] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [formData, setFormData] = useState({
    fullName: "",
    email: "",
    phone: "",
    password: "",
  });

  const { data: users = [], isLoading } = useQuery({
    queryKey: ["users-list"],
    enabled: !loading && role === "admin",
    queryFn: async () => {
      const q = query(collection(db, "users"), orderBy("createdAt", "desc"));
      const snapshot = await getDocs(q);
      return snapshot.docs.map((d) => {
        const data = d.data();
        return {
          id: d.id,
          fullName: data.fullName,
          email: data.email,
          phone: data.phone,
          isActive: data.isActive ?? true,
          createdAt: data.createdAt?.toDate?.() || new Date(),
          role: data.role || "telecaller",
          password: data.password || "Hidden", // only for admin view
        };
      });
    },
  });

  if (!loading && role !== "admin") return <Navigate to="/dashboard" />;

  const handleAddTelecaller = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    try {
      // 1. Check if email already exists in Firestore users
      const usersRef = collection(db, "users");
      const qCheck = query(usersRef, where("email", "==", formData.email));
      const checkSnapshot = await getDocs(qCheck);
      if (!checkSnapshot.empty) {
        throw new Error("A user with this email already exists in the database.");
      }

      // 2. Create the user in Firebase Auth using a Secondary App to avoid logging out the Admin
      const secondaryApp = initializeApp({
        apiKey: "AIzaSyA7tRUWFCTcO1RC0qNMZ3gRTvcLX_K3iAk",
        authDomain: "telecall-crm.firebaseapp.com",
        projectId: "telecall-crm",
      }, "SecondaryAppInstance");
      const secondaryAuth = getAuth(secondaryApp);
      
      const cred = await createUserWithEmailAndPassword(secondaryAuth, formData.email, formData.password);
      const newUid = cred.user.uid;
      
      // Optionally sign out the secondary instance just to be clean
      await secondaryAuth.signOut();

      // 3. Save their profile to Firestore, matching the UID generated by Firebase Auth
      await setDoc(doc(db, "users", newUid), {
        fullName: formData.fullName,
        email: formData.email,
        phone: formData.phone,
        password: formData.password, // Optional: Storing here just so the admin can see it in the UI later
        role: "telecaller",
        isActive: true,
        createdAt: serverTimestamp(),
      });

      toast.success("Telecaller created successfully!");
      setIsAdding(false);
      setFormData({ fullName: "", email: "", phone: "", password: "" });
      queryClient.invalidateQueries({ queryKey: ["users-list"] });
    } catch (error: any) {
      toast.error(error.message || "Failed to create telecaller");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="space-y-5 relative">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h2 className="text-xl font-semibold tracking-tight">User Management</h2>
          <p className="text-sm text-muted-foreground">
            Create and manage telecaller accounts.
          </p>
        </div>
        <Button onClick={() => setIsAdding(true)} className="gap-2">
          <Plus className="h-4 w-4" /> Add Telecaller
        </Button>
      </div>

      <div className="rounded-xl border bg-card shadow-card overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-muted/40 text-muted-foreground">
              <tr className="text-left">
                <th className="px-4 py-3 font-medium">User</th>
                <th className="px-4 py-3 font-medium hidden md:table-cell">Phone</th>
                <th className="px-4 py-3 font-medium">Password</th>
                <th className="px-4 py-3 font-medium">Role</th>
                <th className="px-4 py-3 font-medium">Status</th>
                <th className="px-4 py-3 font-medium hidden md:table-cell">Joined</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              {isLoading && (
                <tr>
                  <td colSpan={6} className="p-6 text-center text-muted-foreground">
                    Loading…
                  </td>
                </tr>
              )}
              {!isLoading && users.length === 0 && (
                <tr>
                  <td colSpan={6} className="p-10 text-center text-muted-foreground">
                    No telecallers yet. Click "Add Telecaller" to create one.
                  </td>
                </tr>
              )}
              {users.map((u: any) => (
                <tr key={u.id} className="hover:bg-muted/30">
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-3">
                      <div className="flex h-9 w-9 items-center justify-center rounded-full bg-gradient-accent text-white text-xs font-semibold">
                        {(u.fullName || u.email || "U").charAt(0).toUpperCase()}
                      </div>
                      <div>
                        <div className="font-medium">{u.fullName || "—"}</div>
                        <div className="text-xs text-muted-foreground">{u.email}</div>
                      </div>
                    </div>
                  </td>
                  <td className="px-4 py-3 hidden md:table-cell">{u.phone || "—"}</td>
                  <td className="px-4 py-3 font-mono text-xs">{u.password}</td>
                  <td className="px-4 py-3">
                    <Badge
                      variant={u.role === "admin" ? "default" : "secondary"}
                      className="capitalize"
                    >
                      {u.role}
                    </Badge>
                  </td>
                  <td className="px-4 py-3">
                    <span
                      className={`text-xs px-2 py-1 rounded-full border ${u.isActive ? "bg-success/15 text-success border-success/30" : "bg-muted text-muted-foreground border-border"}`}
                    >
                      {u.isActive ? "Active" : "Inactive"}
                    </span>
                  </td>
                  <td className="px-4 py-3 hidden md:table-cell text-muted-foreground">
                    {new Date(u.createdAt).toLocaleDateString()}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {isAdding && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
          <div className="bg-background rounded-xl shadow-lg w-full max-w-md overflow-hidden animate-in fade-in zoom-in-95 duration-200">
            <div className="p-4 border-b flex justify-between items-center">
              <h3 className="font-semibold text-lg">Create Telecaller</h3>
              <Button variant="ghost" size="icon" onClick={() => setIsAdding(false)}>
                <X className="h-4 w-4" />
              </Button>
            </div>
            <form onSubmit={handleAddTelecaller} className="p-4 space-y-4">
              <div className="space-y-2">
                <Label htmlFor="fullName">Full Name</Label>
                <Input
                  id="fullName"
                  required
                  value={formData.fullName}
                  onChange={(e) => setFormData({ ...formData, fullName: e.target.value })}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="email">Login Email</Label>
                <Input
                  id="email"
                  type="email"
                  required
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="password">Login Password</Label>
                <Input
                  id="password"
                  required
                  minLength={6}
                  value={formData.password}
                  onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="phone">Phone Number (Optional)</Label>
                <Input
                  id="phone"
                  value={formData.phone}
                  onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
                />
              </div>
              <div className="pt-4 flex justify-end gap-2">
                <Button type="button" variant="outline" onClick={() => setIsAdding(false)}>
                  Cancel
                </Button>
                <Button type="submit" disabled={isSubmitting}>
                  {isSubmitting && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}
                  Create Account
                </Button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
